name: "CI/CD"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Lint"
        run: yarn lint -f @react-hookz/gha

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Build"
        run: yarn build

  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Enable corepack'
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'

      - name: "Install dependencies"
        run: yarn install --immutable

      - name: "Test"
        run:  yarn test:coverage --reporter='github-actions' --reporter='junit' --outputFile='./coverage/test-report.junit.xml' --reporter=default
